apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2  # 복제본 2개 실행
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: react-container
          image: hangyudeok/my-react-app:latest  # 본인의 도커허브 이미지로 변경
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  type: LoadBalancer  # 클라우드 환경에선 외부 접속용, 로컬은 NodePort로 변경 가능
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
